import csv
from pathlib import Path

csv_path = Path(__file__).resolve().parent.parent / "data" / "cases.csv"

cases = [
    {
        "case_id": "NET-001",
        "symptom": "PC1 cannot ping PC2. Both are in the same department but connected to different switches.",
        "topology_note": "PC1 -> SW1 -> SW2 -> PC2",
        "show_outputs": "SW1# show interfaces trunk\nPort   Mode   Encapsulation  Status  Native vlan\nGi0/1  on     802.1q         trunking 1\n\nSW2# show interfaces trunk\nPort   Mode   Encapsulation  Status  Native vlan\nGi0/1  on     802.1q         trunking 1\n\nSW1# show vlan brief\n10   Sales    active    Fa0/1\n\nSW2# show vlan brief\n20   IT       active    Fa0/1",
        "expected_fault": "PC1 and PC2 are assigned to different VLANs (10 and 20) on their respective access ports.",
        "osi_layer": "Layer 2",
        "concept": "VLAN",
        "severity": "Medium",
        "expected_fix": "Reassign switchport Fa0/1 on SW2 to VLAN 10 using switchport access vlan 10.",
        "verification": "show vlan brief on SW2 and ping PC2 from PC1"
    },
    {
        "case_id": "NET-002",
        "symptom": "New PC connected to SW1 Fa0/2 cannot reach the network.",
        "topology_note": "PC -> SW1 (Fa0/2)",
        "show_outputs": "SW1# show vlan brief\n1    default  active    Fa0/1, Fa0/3\n\nSW1# show interfaces Fa0/2 switchport\nName: Fa0/2\nSwitchport: Enabled\nAdministrative Mode: static access\nOperational Mode: static access\nAccess Mode VLAN: 10 (Inactive)",
        "expected_fault": "VLAN 10 is configured on the access port but missing from the VLAN database.",
        "osi_layer": "Layer 2",
        "concept": "VLAN",
        "severity": "Medium",
        "expected_fix": "Create VLAN 10 in global configuration mode on SW1 (vlan 10).",
        "verification": "show vlan brief on SW1 to verify VLAN 10 is active"
    },
    {
        "case_id": "NET-003",
        "symptom": "Traffic from VLAN 30 cannot cross between Switch A and Switch B. Other VLANs work fine.",
        "topology_note": "SW_A -> trunk -> SW_B",
        "show_outputs": "SW_A# show interfaces trunk\nPort        Vlans allowed on trunk\nGi0/1       10,20,30\n\nSW_B# show interfaces trunk\nPort        Vlans allowed on trunk\nGi0/1       10,20",
        "expected_fault": "VLAN 30 is not allowed on the trunk link on Switch B.",
        "osi_layer": "Layer 2",
        "concept": "VLAN",
        "severity": "High",
        "expected_fix": "Add VLAN 30 to the allowed trunk VLAN list on SW_B Gi0/1 (switchport trunk allowed vlan add 30).",
        "verification": "show interfaces trunk on SW_B"
    },
    {
        "case_id": "NET-004",
        "symptom": "CDP messages indicate a 'Native VLAN mismatch' on the trunk between SW1 and SW2.",
        "topology_note": "SW1 (Gi0/1) -> SW2 (Gi0/1)",
        "show_outputs": "SW1# show interfaces Gi0/1 switchport\nTrunking Native Mode VLAN: 99 (Management)\n\nSW2# show interfaces Gi0/1 switchport\nTrunking Native Mode VLAN: 1 (default)",
        "expected_fault": "Native VLAN mismatch across the trunk link (99 vs 1).",
        "osi_layer": "Layer 2",
        "concept": "VLAN",
        "severity": "Low",
        "expected_fix": "Set native VLAN on SW2 interface Gi0/1 to match SW1 (switchport trunk native vlan 99).",
        "verification": "show interfaces Gi0/1 switchport on SW2 and monitor CDP console logs"
    },
    {
        "case_id": "NET-005",
        "symptom": "PC1 can ping other PCs in its subnet but cannot reach the internet or other subnets.",
        "topology_note": "PC1 (192.168.1.50) -> SW1 -> R1 (192.168.1.1)",
        "show_outputs": "C:\\> ipconfig\nIPv4 Address: 192.168.1.50\nSubnet Mask: 255.255.255.0\nDefault Gateway: 192.168.1.254\n\nR1# show ip interface brief\nGigabitEthernet0/0     192.168.1.1     YES manual up                    up",
        "expected_fault": "Incorrect default gateway configured on PC1 (192.168.1.254 instead of 192.168.1.1).",
        "osi_layer": "Layer 3",
        "concept": "Gateway",
        "severity": "High",
        "expected_fix": "Change PC1 default gateway address to 192.168.1.1 in network settings.",
        "verification": "ipconfig on PC1 and ping 192.168.1.1"
    },
    {
        "case_id": "NET-006",
        "symptom": "Entire branch office cannot access the main headquarters network.",
        "topology_note": "Branch PCs -> SW -> R_Branch (Gi0/0)",
        "show_outputs": "R_Branch# show ip interface brief\nInterface              IP-Address      OK? Method Status                Protocol\nGigabitEthernet0/0     10.1.1.1        YES manual administratively down down\nGigabitEthernet0/1     192.168.100.1   YES manual up                    up",
        "expected_fault": "The gateway interface (Gi0/0) on the branch router is administratively down.",
        "osi_layer": "Layer 1",
        "concept": "Gateway",
        "severity": "Critical",
        "expected_fix": "Enter interface GigabitEthernet0/0 configuration mode on R_Branch and execute no shutdown.",
        "verification": "show ip interface brief on R_Branch"
    },
    {
        "case_id": "NET-007",
        "symptom": "Server cannot reach external networks despite seemingly correct IP settings.",
        "topology_note": "Server (10.0.0.10/24) -> Router (10.0.1.1/24)",
        "show_outputs": "Server# ipconfig\nIPv4 Address: 10.0.0.10\nSubnet Mask: 255.255.255.0\nDefault Gateway: 10.0.1.1\n\nRouter# show running-config interface Gi0/0\ninterface GigabitEthernet0/0\n ip address 10.0.1.1 255.255.255.0",
        "expected_fault": "Server's default gateway is on a different subnet (10.0.1.x) than the server's IP (10.0.0.x).",
        "osi_layer": "Layer 3",
        "concept": "Gateway",
        "severity": "High",
        "expected_fix": "Reconfigure server default gateway to an IP inside 10.0.0.0/24 (e.g. 10.0.0.1).",
        "verification": "ipconfig on server and ping 10.0.0.1"
    },
    {
        "case_id": "NET-008",
        "symptom": "New clients connecting to the network fail to get an IP address and receive APIPA addresses instead.",
        "topology_note": "Clients -> SW1 -> R1 (DHCP Server)",
        "show_outputs": "R1# show ip dhcp pool LAN\nPool LAN :\n Utilization mark (high/low)    : 100 / 0\n Subnet size (first/next)       : 0 / 0\n Total addresses                : 50\n Leased addresses               : 50\n Pending event                  : none",
        "expected_fault": "DHCP pool is exhausted; 50/50 addresses are leased.",
        "osi_layer": "Layer 7",
        "concept": "DHCP",
        "severity": "High",
        "expected_fix": "Expand DHCP subnet address pool or clear expired bindings with clear ip dhcp binding *.",
        "verification": "show ip dhcp pool LAN on R1"
    },
    {
        "case_id": "NET-009",
        "symptom": "PCs receive DHCP IP addresses but cannot route traffic off the local subnet.",
        "topology_note": "PCs -> SW1 -> R1 (DHCP)",
        "show_outputs": "R1# show running-config | section dhcp\nip dhcp pool OFFICE\n network 192.168.10.0 255.255.255.0\n default-router 192.168.20.1\n dns-server 8.8.8.8\n\nR1# show ip interface brief\nGi0/0    192.168.10.1    YES manual up    up",
        "expected_fault": "Incorrect default-router in DHCP pool (192.168.20.1 instead of 192.168.10.1).",
        "osi_layer": "Layer 7",
        "concept": "DHCP",
        "severity": "High",
        "expected_fix": "Update DHCP pool configuration on R1 with default-router 192.168.10.1.",
        "verification": "ipconfig /renew on client PC and verify gateway address"
    },
    {
        "case_id": "NET-010",
        "symptom": "Clients on VLAN 20 do not get an IP address. DHCP server is on VLAN 10.",
        "topology_note": "VLAN 20 Clients -> SW (L3) -> DHCP Server (VLAN 10)",
        "show_outputs": "SW# show running-config interface Vlan20\ninterface Vlan20\n ip address 10.0.20.1 255.255.255.0\n ! Missing helper-address\n\nSW# show running-config interface Vlan10\ninterface Vlan10\n ip address 10.0.10.1 255.255.255.0",
        "expected_fault": "Missing ip helper-address on the VLAN 20 interface to forward DHCP broadcasts.",
        "osi_layer": "Layer 3",
        "concept": "DHCP",
        "severity": "Medium",
        "expected_fix": "Configure ip helper-address 10.0.10.2 under interface Vlan20 on SW.",
        "verification": "show running-config interface Vlan20 and ipconfig /renew on client"
    },
    {
        "case_id": "NET-011",
        "symptom": "Occasional IP conflict warnings on the network. Router interfaces sometimes unreachable.",
        "topology_note": "Router provides DHCP for its own attached subnet.",
        "show_outputs": "Router# show running-config | include dhcp\nip dhcp pool LOCAL\n network 192.168.1.0 255.255.255.0\n default-router 192.168.1.1\n\nRouter# show ip dhcp conflict\nIP address        Detection method   Detection time          VRF\n192.168.1.1       Ping               Mar 01 2026 10:00 AM",
        "expected_fault": "Router IP (192.168.1.1) is not excluded from the DHCP pool, causing conflicts.",
        "osi_layer": "Layer 7",
        "concept": "DHCP",
        "severity": "High",
        "expected_fix": "Add ip dhcp excluded-address 192.168.1.1 to global router configuration.",
        "verification": "show running-config | include excluded-address and clear ip dhcp conflict *"
    },
    {
        "case_id": "NET-012",
        "symptom": "Users can ping 8.8.8.8 but cannot browse websites by name.",
        "topology_note": "Users -> Router -> ISP",
        "show_outputs": "C:\\> ping 8.8.8.8\nReply from 8.8.8.8: bytes=32 time=20ms TTL=115\n\nC:\\> ipconfig /all\nDNS Servers . . . . . . . . . . . : 127.0.0.1",
        "expected_fault": "Incorrect DNS server (127.0.0.1) configured via DHCP or statically.",
        "osi_layer": "Layer 7",
        "concept": "DNS",
        "severity": "High",
        "expected_fix": "Update DNS server IP address to a reachable server (e.g. 8.8.8.8 or internal DNS IP).",
        "verification": "nslookup cisco.com on PC"
    },
    {
        "case_id": "NET-013",
        "symptom": "Internal domain names resolve correctly, but external websites do not.",
        "topology_note": "PC -> Internal DNS Server -> Internet",
        "show_outputs": "DNS_Server# show access-lists\nExtended IP access list OUTBOUND\n 10 permit tcp any any eq www\n 20 permit tcp any any eq 443\n 30 deny ip any any\n\nDNS_Server# show run int Gi0/1\ninterface GigabitEthernet0/1\n ip access-group OUTBOUND out",
        "expected_fault": "ACL permits HTTP/HTTPS but denies other IP traffic, which blocks DNS UDP traffic on port 53.",
        "osi_layer": "Layer 4",
        "concept": "DNS",
        "severity": "Medium",
        "expected_fix": "Add permit udp any any eq 53 to extended access-list OUTBOUND on DNS router.",
        "verification": "show access-lists OUTBOUND and nslookup google.com from client"
    },
    {
        "case_id": "NET-014",
        "symptom": "Host fails to resolve names. DNS server is on a different subnet, routing is fine.",
        "topology_note": "Host -> Router -> DNS Server (10.0.0.53)",
        "show_outputs": "Host> ipconfig /all\nDNS Servers . . . . . . . . . . . : 10.0.0.99\n\nRouter# show ip route\nC 192.168.1.0 is directly connected, Gi0/0\nC 10.0.0.0 is directly connected, Gi0/1\n\nHost> ping 10.0.0.99\nRequest timed out.",
        "expected_fault": "The host is configured with an incorrect DNS server IP (10.0.0.99) instead of the actual DNS server (10.0.0.53).",
        "osi_layer": "Layer 3",
        "concept": "DNS",
        "severity": "Medium",
        "expected_fix": "Correct static DNS server address on Host to 10.0.0.53.",
        "verification": "ipconfig /all on host and nslookup lab.local"
    },
    {
        "case_id": "NET-015",
        "symptom": "PC at branch office cannot reach the head office server subnet (10.0.0.0/24).",
        "topology_note": "Branch (192.168.1.0/24) -> R1 (172.16.0.1) -> R2 (172.16.0.2) -> HQ (10.0.0.0/24)",
        "show_outputs": "R1# show ip route\nC 192.168.1.0/24 is directly connected\nC 172.16.0.0/30 is directly connected\n! Note: 10.0.0.0/24 is missing\n\nR2# show ip route\nC 10.0.0.0/24 is directly connected, Gi0/1\nC 172.16.0.0/30 is directly connected, Gi0/0\n\nR1# ping 10.0.0.10\n.....\nSuccess rate is 0 percent (0/5)",
        "expected_fault": "Missing static route to 10.0.0.0/24 on R1.",
        "osi_layer": "Layer 3",
        "concept": "Routing",
        "severity": "Critical",
        "expected_fix": "Configure static route on R1: ip route 10.0.0.0 255.255.255.0 172.16.0.2.",
        "verification": "show ip route on R1 and ping 10.0.0.10 from R1"
    },
    {
        "case_id": "NET-016",
        "symptom": "Internet access is down for all users on R1.",
        "topology_note": "R1 (Gi0/0: 10.1.1.2) -> ISP Router (Gi0/0: 10.1.1.1)",
        "show_outputs": "R1# show running-config | include ip route\nip route 0.0.0.0 0.0.0.0 10.1.1.254\n\nR1# show ip interface brief\nGi0/0  10.1.1.2  YES manual up up",
        "expected_fault": "Incorrect static default route next-hop (10.1.1.254 instead of 10.1.1.1).",
        "osi_layer": "Layer 3",
        "concept": "Routing",
        "severity": "Critical",
        "expected_fix": "Reconfigure static default route on R1: ip route 0.0.0.0 0.0.0.0 10.1.1.1.",
        "verification": "show ip route on R1 and ping 10.1.1.1"
    },
    {
        "case_id": "NET-017",
        "symptom": "OSPF neighbor relationship is not forming between R1 and R2.",
        "topology_note": "R1 (192.168.12.1) <-> R2 (192.168.12.2)",
        "show_outputs": "R1# show running-config | section ospf\nrouter ospf 1\n network 10.0.0.0 0.0.0.255 area 0\n\nR1# show ip interface brief\nGi0/0   192.168.12.1   YES manual up up\n\nR2# show ip ospf neighbor\n(no output)",
        "expected_fault": "Missing OSPF network command for the 192.168.12.0 network on R1.",
        "osi_layer": "Layer 3",
        "concept": "Routing",
        "severity": "High",
        "expected_fix": "Add network 192.168.12.0 0.0.0.255 area 0 under router ospf 1 on R1.",
        "verification": "show ip ospf neighbor on R1 and R2"
    },
    {
        "case_id": "NET-018",
        "symptom": "EIGRP routing table on R1 does not contain routes from R2.",
        "topology_note": "R1 <-> R2",
        "show_outputs": "R1# show ip protocols\nRouting Protocol is 'eigrp 100'\n\nR2# show ip protocols\nRouting Protocol is 'eigrp 200'",
        "expected_fault": "EIGRP Autonomous System (AS) number mismatch (100 vs 200).",
        "osi_layer": "Layer 3",
        "concept": "Routing",
        "severity": "High",
        "expected_fix": "Change EIGRP AS number on R2 to match R1 (router eigrp 100).",
        "verification": "show ip eigrp neighbors on R1"
    },
    {
        "case_id": "NET-019",
        "symptom": "R2 receives no RIP updates from R1 on their connecting link Gi0/1.",
        "topology_note": "R1 (Gi0/1) <-> R2 (Gi0/1)",
        "show_outputs": "R1# show running-config | section router rip\nrouter rip\n version 2\n passive-interface GigabitEthernet0/1\n network 10.0.0.0\n network 192.168.1.0",
        "expected_fault": "Passive-interface is incorrectly configured on the link connecting to R2 (Gi0/1).",
        "osi_layer": "Layer 3",
        "concept": "Routing",
        "severity": "Medium",
        "expected_fix": "Remove passive-interface GigabitEthernet0/1 under router rip process on R1.",
        "verification": "show ip route rip on R2"
    },
    {
        "case_id": "NET-020",
        "symptom": "Users on 192.168.1.0 cannot access the web server at 10.0.0.80 over HTTP.",
        "topology_note": "Users -> R1 (Gi0/1) -> Web Server",
        "show_outputs": "R1# show access-lists\nExtended IP access list 101\n 10 deny tcp 192.168.1.0 0.0.0.255 host 10.0.0.80 eq www (15 matches)\n 20 permit ip any any\n\nR1# show ip interface Gi0/1\n  Outgoing access list is 101",
        "expected_fault": "ACL 101 is applied outbound on Gi0/1 and explicitly denies HTTP traffic from the user subnet to the web server.",
        "osi_layer": "Layer 4",
        "concept": "ACL",
        "severity": "High",
        "expected_fix": "Modify ACL 101 to permit TCP port 80 traffic to 10.0.0.80 or remove deny entry 10.",
        "verification": "show access-lists 101 and HTTP query to 10.0.0.80"
    },
    {
        "case_id": "NET-021",
        "symptom": "PC1 (10.1.1.10) cannot reach the Internet, but it CAN reach the local printer (10.1.1.20).",
        "topology_note": "PC1 -> R1 (Gi0/0) -> Internet. Printer is on R1 Gi0/0.",
        "show_outputs": "R1# show access-lists 1\nStandard IP access list 1\n 10 deny 10.1.1.10\n 20 permit any\n\nR1# show running-config interface Gi0/0\ninterface GigabitEthernet0/0\n ip access-group 1 in",
        "expected_fault": "Standard ACL 1 is applied closest to the source (Gi0/0 in), blocking PC1 from reaching all other networks instead of just a specific destination.",
        "osi_layer": "Layer 3",
        "concept": "ACL",
        "severity": "Medium",
        "expected_fix": "Remove ip access-group 1 in from Gi0/0 and apply specific extended ACL closer to destination.",
        "verification": "show ip interface Gi0/0 and ping 8.8.8.8 from PC1"
    },
    {
        "case_id": "NET-022",
        "symptom": "External SSH access to the admin jump server (192.168.50.5) is failing.",
        "topology_note": "Internet -> R1 (Gi0/0) -> Jump Server",
        "show_outputs": "R1# show access-lists 110\nExtended IP access list 110\n 10 permit tcp host 192.168.50.5 any eq 22  ! Incorrect\n ! Intended: permit tcp any host 192.168.50.5 eq 22\n 20 deny ip any any\n\nR1# show ip interface Gi0/0\n  Inbound access list is 110",
        "expected_fault": "Extended ACL 110 has the source and destination IP/ports reversed for inbound traffic.",
        "osi_layer": "Layer 4",
        "concept": "ACL",
        "severity": "High",
        "expected_fix": "Update entry 10 in ACL 110 to permit tcp any host 192.168.50.5 eq 22.",
        "verification": "show access-lists 110 and test SSH connection"
    },
    {
        "case_id": "NET-023",
        "symptom": "Ping from internal network to external server fails. ACL 100 is designed to block external pings inbound.",
        "topology_note": "Internal -> R1 (Gi0/1) -> (Gi0/0) External",
        "show_outputs": "R1# show running-config interface Gi0/1\ninterface GigabitEthernet0/1\n ip access-group 100 in\n\nR1# show access-lists 100\nExtended IP access list 100\n 10 deny icmp any any echo-request\n 20 permit ip any any",
        "expected_fault": "ACL 100 is applied in the wrong direction or wrong interface (applied IN on the internal interface instead of IN on external).",
        "osi_layer": "Layer 3",
        "concept": "ACL",
        "severity": "Medium",
        "expected_fix": "Remove access-group 100 from Gi0/1 and apply ip access-group 100 in on external interface Gi0/0.",
        "verification": "show ip interface Gi0/1 and ping external IP from internal PC"
    },
    {
        "case_id": "NET-024",
        "symptom": "Internal users cannot reach the internet. NAT overload is configured.",
        "topology_note": "Internal (Gi0/1) -> R1 -> External (Gi0/0)",
        "show_outputs": "R1# show running-config | include ip nat\nip nat inside source list 1 interface GigabitEthernet0/0 overload\n\nR1# show running-config interface Gi0/0\ninterface GigabitEthernet0/0\n ip nat outside\n\nR1# show running-config interface Gi0/1\ninterface GigabitEthernet0/1\n ! Missing ip nat inside",
        "expected_fault": "Missing 'ip nat inside' command on the internal interface Gi0/1.",
        "osi_layer": "Layer 3",
        "concept": "NAT",
        "severity": "High",
        "expected_fix": "Add ip nat inside to interface GigabitEthernet0/1 configuration on R1.",
        "verification": "show running-config interface Gi0/1 and show ip nat translations"
    },
    {
        "case_id": "NET-025",
        "symptom": "Only one internal user can access the internet at a time.",
        "topology_note": "Internal -> R1 -> Internet",
        "show_outputs": "R1# show running-config | include ip nat inside source\nip nat inside source list 1 interface GigabitEthernet0/0\n\nR1# show ip nat translations\nPro Inside global      Inside local       Outside local      Outside global\ntcp 203.0.113.1:80     192.168.1.10:80    198.51.100.1:80    198.51.100.1:80",
        "expected_fault": "The 'overload' keyword is missing from the NAT configuration, preventing PAT.",
        "osi_layer": "Layer 4",
        "concept": "NAT",
        "severity": "High",
        "expected_fix": "Reconfigure NAT rule to include overload: ip nat inside source list 1 interface Gi0/0 overload.",
        "verification": "show ip nat translations with multiple internal users"
    },
    {
        "case_id": "NET-026",
        "symptom": "Users on the new VLAN 20 (192.168.20.0/24) cannot reach the internet, while VLAN 10 users can.",
        "topology_note": "VLAN 10/20 -> R1 -> Internet",
        "show_outputs": "R1# show access-lists 1\nStandard IP access list 1\n 10 permit 192.168.10.0, wildcard bits 0.0.0.255\n\nR1# show running-config | include nat\nip nat inside source list 1 interface Gi0/0 overload",
        "expected_fault": "The NAT ACL (list 1) does not permit the new VLAN 20 subnet.",
        "osi_layer": "Layer 3",
        "concept": "NAT",
        "severity": "Medium",
        "expected_fix": "Add access-list 1 permit 192.168.20.0 0.0.0.255 to NAT ACL on R1.",
        "verification": "show access-lists 1 and ping external IP from VLAN 20 PC"
    },
    {
        "case_id": "NET-027",
        "symptom": "Wireless clients connect to the 'Guest' SSID but receive IPs from the Corporate VLAN (VLAN 10).",
        "topology_note": "WLC -> SW1. Guest WLAN should be VLAN 50.",
        "show_outputs": "WLC> show wlan 2\nWLAN Identifier.................................. 2\nProfile Name..................................... Guest\nNetwork Name (SSID).............................. Guest\nInterface........................................ management (VLAN 10)",
        "expected_fault": "Guest WLAN is incorrectly mapped to the management interface/VLAN 10 instead of the Guest dynamic interface/VLAN 50.",
        "osi_layer": "Layer 2",
        "concept": "Wireless",
        "severity": "High",
        "expected_fix": "Update WLAN 2 interface mapping on WLC to dynamic interface Guest-VLAN50.",
        "verification": "show wlan 2 on WLC and ipconfig on guest client"
    },
    {
        "case_id": "NET-028",
        "symptom": "Clients cannot join the 'CorpWiFi' SSID. They are prompted for a username/password but expect a PSK.",
        "topology_note": "Laptop -> AP -> WLC",
        "show_outputs": "WLC> show wlan 1\nWLAN Identifier.................................. 1\nProfile Name..................................... CorpWiFi\nSecurity Policies:\n WPA2 Encryption.............................. AES\n Auth Key Management.......................... 802.1x\n\nLaptop (User Report):\n'I am typing the pre-shared key but it fails.'",
        "expected_fault": "WLAN is configured for 802.1x (Enterprise) authentication, but the user is expecting a WPA2 PSK.",
        "osi_layer": "Layer 2",
        "concept": "Wireless",
        "severity": "Medium",
        "expected_fix": "Change WLAN 1 Layer 2 security Auth Key Management to PSK and enter pre-shared key.",
        "verification": "show wlan 1 on WLC"
    },
    {
        "case_id": "NET-029",
        "symptom": "Wireless clients connecting to 'Guest-Net' fail to obtain IP address from DHCP server on WLC.",
        "topology_note": "Guest Laptop -> Lightweight AP -> WLC (DHCP Server)",
        "show_outputs": "WLC> show dhcp summary\nScope Name: GuestPool\nNetwork: 172.16.50.0/24\nDefault Router: 172.16.50.254\nStatus: Disabled",
        "expected_fault": "Internal DHCP scope for Guest wireless clients is administratively disabled on Wireless LAN Controller.",
        "osi_layer": "Layer 7",
        "concept": "Wireless",
        "severity": "Medium",
        "expected_fix": "Enable DHCP scope GuestPool on WLC with config dhcp scope enable GuestPool.",
        "verification": "show dhcp summary on WLC and ipconfig /renew on guest client"
    },
    {
        "case_id": "NET-030",
        "symptom": "Guest Wi-Fi users connected to 'Guest-WiFi' can reach sensitive internal corporate server (10.0.0.10).",
        "topology_note": "Guest Laptop -> AP -> WLC -> Core Switch -> Corporate Server (10.0.0.10)",
        "show_outputs": "WLC> show wlan 3\nSSID: Guest-WiFi\nInterface: guest-vlan50\nClient ACL: None\n\nCore Switch# show access-lists GUEST_BLOCK\nExtended IP access list GUEST_BLOCK\n 10 deny ip 172.16.50.0 0.0.0.255 10.0.0.0 0.255.255.255\n 20 permit ip any any\n\nCore Switch# show ip interface Vlan50\n Inbound access list is Not set",
        "expected_fault": "Guest isolation ACL GUEST_BLOCK is created on Core Switch but not applied inbound on interface Vlan50.",
        "osi_layer": "Layer 3",
        "concept": "Wireless",
        "severity": "High",
        "expected_fix": "Apply ACL inbound on Vlan50 interface (interface Vlan50, ip access-group GUEST_BLOCK in).",
        "verification": "show ip interface Vlan50 and ping 10.0.0.10 from guest host"
    },
    {
        "case_id": "NET-031",
        "symptom": "Host connected to SW1 Fa0/5 cannot communicate with other devices in VLAN 20.",
        "topology_note": "Host_C -> SW1 (Fa0/5) -> Trunk -> Core Router",
        "show_outputs": "SW1# show vlan brief\n1    default          active    Fa0/1, Fa0/5\n20   SERVERS          active    Fa0/2, Fa0/3\n\nSW1# show interfaces Fa0/5 switchport\nName: Fa0/5\nSwitchport: Enabled\nAdministrative Mode: static access\nOperational Mode: static access\nAccess Mode VLAN: 1 (default)",
        "expected_fault": "Interface Fa0/5 on SW1 is assigned to default VLAN 1 instead of VLAN 20.",
        "osi_layer": "Layer 2",
        "concept": "VLAN",
        "severity": "Medium",
        "expected_fix": "Configure switchport access vlan 20 on interface Fa0/5 on SW1.",
        "verification": "show interfaces Fa0/5 switchport on SW1"
    },
    {
        "case_id": "NET-032",
        "symptom": "Hosts on VLAN 20 cannot reach remote subnets via Router-on-a-Stick subinterface.",
        "topology_note": "VLAN 20 Hosts -> Switch -> Router (Gi0/0.20 subinterface)",
        "show_outputs": "Router# show running-config interface Gi0/0.20\ninterface GigabitEthernet0/0.20\n ip address 192.168.20.1 255.255.255.0\n ! Missing encapsulation dot1Q 20\n\nRouter# show ip interface brief\nGi0/0.20      192.168.20.1    YES manual up                    down",
        "expected_fault": "Subinterface Gi0/0.20 is missing encapsulation dot1Q 20, causing line protocol to remain down.",
        "osi_layer": "Layer 3",
        "concept": "Gateway",
        "severity": "High",
        "expected_fix": "Configure encapsulation dot1Q 20 under subinterface Gi0/0.20 on Router.",
        "verification": "show ip interface brief on Router"
    },
    {
        "case_id": "NET-033",
        "symptom": "DHCP clients receive IP addresses in the 192.168.2.0/24 subnet instead of local 192.168.1.0/24 subnet.",
        "topology_note": "Branch PC -> Switch -> Branch Router (DHCP Server)",
        "show_outputs": "Branch_Router# show running-config | section dhcp\nip dhcp pool BRANCH\n network 192.168.2.0 255.255.255.0\n default-router 192.168.1.1\n dns-server 8.8.8.8\n\nBranch_Router# show ip interface brief\nGi0/0         192.168.1.1     YES manual up                    up",
        "expected_fault": "Network statement in DHCP pool is configured for the wrong subnet (192.168.2.0/24 instead of 192.168.1.0/24).",
        "osi_layer": "Layer 7",
        "concept": "DHCP",
        "severity": "Medium",
        "expected_fix": "Update DHCP pool network statement to network 192.168.1.0 255.255.255.0.",
        "verification": "ipconfig /renew on client PC"
    },
    {
        "case_id": "NET-034",
        "symptom": "Cisco IOS Router fails to resolve domain names when using diagnostic commands like ping host.domain.com.",
        "topology_note": "Router R1 -> ISP Router (8.8.8.8 reachable)",
        "show_outputs": "R1# show running-config | include ip domain\n! No ip domain-name or ip name-server configured\n\nR1# ping google.com\nTranslating \"google.com\"...domain server (255.255.255.255)\n% Unrecognized host or address, or protocol not running.",
        "expected_fault": "DNS domain lookup and name-server IP (8.8.8.8) are not configured on router R1.",
        "osi_layer": "Layer 7",
        "concept": "DNS",
        "severity": "Low",
        "expected_fix": "Configure ip domain-lookup and ip name-server 8.8.8.8 on router R1.",
        "verification": "ping google.com from R1"
    },
    {
        "case_id": "NET-035",
        "symptom": "External web clients cannot access internal web server at 192.168.1.100 via public IP 203.0.113.10.",
        "topology_note": "External Client -> Router R1 (Public IP 203.0.113.10) -> Web Server (192.168.1.100)",
        "show_outputs": "R1# show running-config | include ip nat inside source static\nip nat inside source static 192.168.1.50 203.0.113.10\n\nR1# show ip interface brief\nGi0/0         203.0.113.10    YES manual up                    up\nGi0/1         192.168.1.1     YES manual up                    up\n\nServer# ipconfig\nIPv4 Address: 192.168.1.100",
        "expected_fault": "Static NAT rule maps public IP 203.0.113.10 to incorrect internal IP address (192.168.1.50 instead of 192.168.1.100).",
        "osi_layer": "Layer 3",
        "concept": "NAT",
        "severity": "High",
        "expected_fix": "Update static NAT rule: ip nat inside source static 192.168.1.100 203.0.113.10.",
        "verification": "show ip nat translations and HTTP query to 203.0.113.10"
    }
]

with open(csv_path, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=cases[0].keys(), quoting=csv.QUOTE_MINIMAL)
    writer.writeheader()
    writer.writerows(cases)

print(f"Successfully formatted and wrote {len(cases)} cases to {csv_path}")
